version: "3.1"

services:
  wordpress:
    image: wordpress
    container_name: plant_wordpress
    restart: always
    ports:
      - 8123:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
      - ~/Documents/plantNetwork/wp-themes:/var/www/html/wp-content/themes
      - ~/Documents/plantNetwork/wp-config.php:/var/www/html/wp-config.php

  db:
    image: mysql:8.0
    container_name: plant_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
